"""Create a Linux-installable copy of the pinned ok-script wheel.

ok-script 2.0.7b1 is a pure-Python wheel, but its core metadata declares three
Windows-only runtime packages without platform markers.  The cloud bridge does
not import those native backends.  This build-only tool verifies the exact
upstream artifact and removes only those dependency declarations from a copied
wheel; it never edits the host interpreter or an installed package.
"""

from __future__ import annotations

import base64
import csv
import hashlib
import io
import sys
import zipfile
from pathlib import Path


EXPECTED_FILENAME = "ok_script-2.0.7b1-py3-none-any.whl"
EXPECTED_SHA256 = "7d9b9570d22390f9edcd612ea2a700e9365b8706318caeb6e520f7228de1fe75"
METADATA_PATH = "ok_script-2.0.7b1.dist-info/METADATA"
RECORD_PATH = "ok_script-2.0.7b1.dist-info/RECORD"
CAPTURE_INIT_PATH = "ok/device/capture_methods/__init__.py"
CAPTURE_COMPAT_PATH = "ok/device/capture.py"
INTERACTION_INIT_PATH = "ok/device/interaction_methods/__init__.py"
OK_INIT_PATH = "ok/__init__.py"
LINUX_COMPAT_PATH = "ok/linux_cloud_compat.py"
WINDOW_UTIL_PATH = "ok/util/window.py"
SCREENSHOT_PATH = "ok/core/screenshot.py"
NOTIFICATION_MANAGER_PATH = "ok/notification/manager.py"
PROCESS_UTIL_PATH = "ok/util/process.py"
# The first three packages implement native Windows backends.  ``mouse`` and
# ``pynput`` are cross-platform packages, but ok-script only imports them from
# native/Qt interaction tooling that the Playwright bridge replaces.  Removing
# all five avoids installing an unused host-input stack inside the container.
REMOVED_DEPENDENCIES = frozenset(
    {"pywin32", "pycaw", "pydirectinput", "mouse", "pynput"}
)
LINUX_CAPTURE_INIT = b"""\
\"\"\"Linux cloud subset; generated by ok-wuthering-waves Docker build.\"\"\"\n
from ok.device.capture_methods.base import BaseCaptureMethod, BaseWindowsCaptureMethod\n
__all__ = [\"BaseCaptureMethod\", \"BaseWindowsCaptureMethod\"]\n
"""
LINUX_CAPTURE_COMPAT = b"""\
\"\"\"Linux cloud capture compatibility exports.\"\"\"\n
from ok.device.capture_methods.base import BaseCaptureMethod, BaseWindowsCaptureMethod\n
\n
class BrowserCaptureMethod(BaseCaptureMethod):\n
    pass\n
\n
__all__ = [\"BaseCaptureMethod\", \"BaseWindowsCaptureMethod\", \"BrowserCaptureMethod\"]\n
"""
LINUX_INTERACTION_INIT = b"""\
\"\"\"Linux cloud subset; generated by ok-wuthering-waves Docker build.\"\"\"\n
from ok.device.interaction_methods.base import BaseInteraction\n
__all__ = [\"BaseInteraction\"]\n
"""
LINUX_COMPAT = b"""\
\"\"\"Platform probes used by the Linux cloud runtime.\"\"\"\n
def windows_graphics_available():\n
    return False\n
"""


def _patch_ok_init(raw: bytes) -> bytes:
    source = raw.decode("utf-8")
    old_mapping = "'windows_graphics_available': ('ok.util.window', 'windows_graphics_available'),"
    new_mapping = "'windows_graphics_available': ('ok.linux_cloud_compat', 'windows_graphics_available'),"
    old_dpi = """        try:
            import ctypes
            # Set DPI Awareness (Windows 10 and 8)
            errorCode = ctypes.windll.shcore.SetProcessDpiAwareness(2)
            logger.info(f'SetProcessDpiAwareness {errorCode}')
            if self.debug:
                import win32api
                win32api.SetConsoleCtrlHandler(self.console_handler, True)
        except Exception as e:
            logger.error(f'SetProcessDpiAwareness error', e)
"""
    new_dpi = """        if sys.platform == 'win32':
            try:
                import ctypes
                # Set DPI Awareness (Windows 10 and 8)
                errorCode = ctypes.windll.shcore.SetProcessDpiAwareness(2)
                logger.info(f'SetProcessDpiAwareness {errorCode}')
                if self.debug:
                    import win32api
                    win32api.SetConsoleCtrlHandler(self.console_handler, True)
            except Exception as e:
                logger.error(f'SetProcessDpiAwareness error', e)
"""
    if source.count(old_mapping) != 1:
        raise RuntimeError("unexpected ok/__init__.py windows graphics mapping")
    if source.count(old_dpi) != 1:
        raise RuntimeError("unexpected ok/__init__.py DPI initialization")
    return source.replace(old_mapping, new_mapping).replace(old_dpi, new_dpi).encode("utf-8")


def _patch_window_util(raw: bytes) -> bytes:
    source = raw.decode("utf-8")
    old_imports = """import win32api
import win32con
import win32gui
import win32process
"""
    new_imports = """if sys.platform == \"win32\":
    import win32api
    import win32con
    import win32gui
    import win32process
else:
    win32api = win32con = win32gui = win32process = None
"""
    old_user32 = "user32 = ctypes.WinDLL('user32', use_last_error=True)"
    new_user32 = "user32 = ctypes.WinDLL('user32', use_last_error=True) if sys.platform == \"win32\" else None"
    if source.count(old_imports) != 1 or source.count(old_user32) != 1:
        raise RuntimeError("unexpected ok/util/window.py platform imports")
    return source.replace(old_imports, new_imports).replace(old_user32, new_user32).encode("utf-8")


def _patch_screenshot(raw: bytes) -> bytes:
    source = raw.decode("utf-8")
    old = """            fonts_dir = os.path.join(os.environ['WINDIR'], 'Fonts')
            font = find_first_existing_file(
                ['msyh.ttc', 'msyh.ttf', 'simsun.ttf', 'simsun.ttc', 'arial.ttf', 'arial.ttc'], fonts_dir)
"""
    new = """            if os.name == 'nt':
                fonts_dir = os.path.join(os.environ['WINDIR'], 'Fonts')
                font_names = ['msyh.ttc', 'msyh.ttf', 'simsun.ttf', 'simsun.ttc', 'arial.ttf', 'arial.ttc']
            else:
                fonts_dir = '/usr/share/fonts/opentype/noto'
                font_names = ['NotoSansCJK-Regular.ttc']
            font = find_first_existing_file(font_names, fonts_dir)
"""
    if source.count(old) != 1:
        raise RuntimeError("unexpected ok/core/screenshot.py font lookup")
    return source.replace(old, new).encode("utf-8")


def _patch_notification_manager(raw: bytes) -> bytes:
    source = raw.decode("utf-8")
    eager = "from ok.notification.windows_messenger import MessengerAutomation\n"
    if source.count(eager) != 1:
        raise RuntimeError("unexpected ok/notification/manager.py messenger import")
    source = source.replace(eager, "")
    marker = "        messenger_message = self._messenger_message(title, message)\n"
    lazy = marker + "        if self.config.get(QQ_NOTIFICATION_ENABLED) or self.config.get(WECHAT_NOTIFICATION_ENABLED):\n            from ok.notification.windows_messenger import MessengerAutomation\n"
    if source.count(marker) != 1:
        raise RuntimeError("unexpected notification messenger setup")
    return source.replace(marker, lazy).encode("utf-8")


def _patch_process_util(raw: bytes) -> bytes:
    source = raw.decode("utf-8")
    old = """def prevent_sleeping(yes=True):
    # Prevent the system from sleeping
    ctypes.windll.kernel32.SetThreadExecutionState(0x80000002 if yes else 0x80000000)
"""
    new = """def prevent_sleeping(yes=True):
    # Containers have no Windows power-management API to call.
    if sys.platform != 'win32':
        return
    ctypes.windll.kernel32.SetThreadExecutionState(0x80000002 if yes else 0x80000000)
"""
    if source.count(old) != 1:
        raise RuntimeError("unexpected ok/util/process.py sleep prevention")
    return source.replace(old, new).encode("utf-8")


def _dependency_name(line: str) -> str | None:
    prefix = "Requires-Dist: "
    if not line.startswith(prefix):
        return None
    requirement = line[len(prefix) :].strip()
    name = requirement.split(";", 1)[0].split("[", 1)[0]
    for separator in (" ", "<", ">", "=", "!", "~"):
        name = name.split(separator, 1)[0]
    return name.strip().lower()


def _patch_metadata(raw: bytes) -> bytes:
    text = raw.decode("utf-8")
    lines = text.splitlines(keepends=True)
    removed: set[str] = set()
    kept: list[str] = []
    for line in lines:
        dependency = _dependency_name(line)
        if dependency in REMOVED_DEPENDENCIES:
            removed.add(dependency)
            continue
        kept.append(line)
    if removed != REMOVED_DEPENDENCIES:
        missing = ", ".join(sorted(REMOVED_DEPENDENCIES - removed))
        raise RuntimeError(f"expected Windows-only dependencies were absent: {missing}")
    marker = "X-Ok-WW-Compatibility: linux-cloud-1\n"
    insert_at = next(
        (index for index, line in enumerate(kept) if line.strip() == ""),
        len(kept),
    )
    kept.insert(insert_at, marker)
    return "".join(kept).encode("utf-8")


def _record_bytes(contents: dict[str, bytes]) -> bytes:
    stream = io.StringIO(newline="")
    writer = csv.writer(stream, lineterminator="\n")
    for name in sorted(contents):
        if name == RECORD_PATH:
            continue
        digest = hashlib.sha256(contents[name]).digest()
        encoded = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
        writer.writerow((name, f"sha256={encoded}", len(contents[name])))
    writer.writerow((RECORD_PATH, "", ""))
    return stream.getvalue().encode("utf-8")


def patch_wheel(source: Path, destination_dir: Path) -> Path:
    if source.name != EXPECTED_FILENAME:
        raise RuntimeError(f"unexpected wheel name: {source.name}")
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    if digest != EXPECTED_SHA256:
        raise RuntimeError(
            f"unexpected {EXPECTED_FILENAME} sha256: {digest}; "
            f"expected {EXPECTED_SHA256}"
        )

    with zipfile.ZipFile(source) as archive:
        contents = {name: archive.read(name) for name in archive.namelist()}
    required_paths = {
        METADATA_PATH,
        RECORD_PATH,
        CAPTURE_INIT_PATH,
        CAPTURE_COMPAT_PATH,
        INTERACTION_INIT_PATH,
        OK_INIT_PATH,
        WINDOW_UTIL_PATH,
        SCREENSHOT_PATH,
        NOTIFICATION_MANAGER_PATH,
        PROCESS_UTIL_PATH,
    }
    missing_paths = required_paths - contents.keys()
    if missing_paths:
        raise RuntimeError(
            "ok-script wheel does not contain expected files: "
            + ", ".join(sorted(missing_paths))
        )
    contents[METADATA_PATH] = _patch_metadata(contents[METADATA_PATH])
    # Importing a submodule executes its package __init__ first.  The upstream
    # aggregate initializers eagerly import every native Windows backend, so
    # expose only the neutral base classes used by the external cloud bridge.
    contents[CAPTURE_INIT_PATH] = LINUX_CAPTURE_INIT
    contents[CAPTURE_COMPAT_PATH] = LINUX_CAPTURE_COMPAT
    contents[INTERACTION_INIT_PATH] = LINUX_INTERACTION_INIT
    contents[OK_INIT_PATH] = _patch_ok_init(contents[OK_INIT_PATH])
    contents[WINDOW_UTIL_PATH] = _patch_window_util(contents[WINDOW_UTIL_PATH])
    contents[SCREENSHOT_PATH] = _patch_screenshot(contents[SCREENSHOT_PATH])
    contents[NOTIFICATION_MANAGER_PATH] = _patch_notification_manager(
        contents[NOTIFICATION_MANAGER_PATH]
    )
    contents[PROCESS_UTIL_PATH] = _patch_process_util(contents[PROCESS_UTIL_PATH])
    contents[LINUX_COMPAT_PATH] = LINUX_COMPAT
    contents[RECORD_PATH] = _record_bytes(contents)

    destination_dir.mkdir(parents=True, exist_ok=True)
    destination = destination_dir / source.name
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name in sorted(contents):
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, contents[name])
    return destination


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"usage: {argv[0]} SOURCE_WHEEL DESTINATION_DIR", file=sys.stderr)
        return 2
    print(patch_wheel(Path(argv[1]), Path(argv[2])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
